language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

script:
  - make ci
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js > /dev/null 2>&1

before_script:
  - npm i -g npm
